### ISSUE TITLE
Изменения в 1С

### ISSUE THREAD

**Issue by unpete** [oknosoft/common-catalogs#1]
читаем [readme](https://github.com/oknosoft/common-catalogs/blob/master/README.md)

![image](https://user-images.githubusercontent.com/12096477/63223647-83cc2d80-c1d2-11e9-9ba1-24d044583ebc.png)
- Вместо списка значений `Базы обмена`, явное перечисление баз и абонентов на закладке `Загрузка`
- Кроме числового значения номера зоны, в поле zone загрузки можно указать абонента или сервер общих данных
- Загрузка в регламентном задании выполняется по списку отмеченных галкой баз
- Редактирование типов данных, помеченных, как общие данные на стороне 1С отключено - изменения делаются в сервисе и разбегаются по всем подписчикам

![image](https://user-images.githubusercontent.com/12096477/63223664-d6a5e500-c1d2-11e9-9d8b-5fe1e0975a4e.png)

**Comment by senitskiy** [comment]
До обновления работало два метода выгрузки Маржинальных коэффициэнтов {МК}:
1) непосредственно при записи, срабатывала подписка на событие для текущего абонента в настройках интеграции;
2) выгрузка в обр. интеграция-настройка для конкретного абонента.

Теперь не работает ни один:
1) в ом.ИнтеграцияСерелизацияСервер (в стр. 1354, 1453) Функция МенеджерИМетаПоСтрокеТипа не обрабатывает ireg, иначе тоже нет. Предлагаю дополнить.
2) более детально попробую описать исходя, из кода.

**Comment by unpete** [comment]
> описать исходя, из кода.

Спасибо, достаточно описания проблемы. Там много режимов работы, которые в Экоокнах не используются. Для всей мозаики, у вас не хватит данных.

**Comment by unpete** [comment]
dev и prod обновил - проверяйте. cf в google-drive так же, обновил.
Проблема, как вы и предполагали, была в методе МенеджерИМетаПоСтрокеТипа.
До включения общих данных, регистры выгружались в базу по умолчанию без учета правил, заданных в настройках meta.

По хорошему, курсы валют и маржинальные коэффициенты надо регистрировать при записи в базах всех абонентов с фильтром по типам цен. В Экоокнах это, наверное, решается при регистрации среза цен или средствами mdm или руками оператора. Если актуально - говорите, поставлю в план.

**Comment by senitskiy** [comment]
а можно ссылку на google-drive?

**Comment by unpete** [comment]
@senitskiy, у вас [email в профиле](https://github.com/senitskiy) не указан. Куда ссылку то отправлять?

**Comment by senitskiy** [comment]
добавил
